# Generated by Django 5.2.8 on 2025-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medio_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField()),
                ('comprobante', models.CharField()),
                ('fecha', models.CharField()),
                ('hora', models.CharField()),
            ],
        ),
    ]
