# Generated by Django 5.2.8 on 2025-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talles', models.CharField()),
                ('Diseño_a_elección', models.CharField()),
                ('Tamaño_de_estampa', models.CharField()),
                ('Corte', models.CharField()),
            ],
        ),
    ]
