# Generated by Django 5.2.8 on 2025-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField()),
                ('telefono', models.IntegerField(max_length=100)),
                ('correo', models.CharField()),
                ('direccion', models.CharField()),
            ],
        ),
    ]
