# Generated by Django 5.2.8 on 2025-11-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Indumentaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField()),
                ('hora', models.CharField()),
                ('Descripción', models.CharField()),
                ('id_indumentaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indumentaria.indumentaria')),
            ],
        ),
    ]
